name: Waka Readme

on:
  schedule:
    # Runs at 0:00 UTC+8
    - cron: '8 16 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_COMMIT: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_UPDATED_DATE: "False"
          IGNORED_REPOS: "YinY1"
          SYMBOL_VERSION: "3"
